baseURL = "https://programmador.com/"
theme = "console"
title = "i.e.g."
languageCode = "en"

[params]
  titleCutting = false
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "about/"
  url = "about"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "tags/"
  url = "tags/"
