baseURL: "https://programmador.com/"
title: programmador.com
paginate: 5
theme: PaperMod
copyright: >
  © 2022-2023 [Ivan Eduardo
  Guerra](https://github.com/ivan-guerra/programmador.com/blob/master/LICENSE)

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: programmador.com
  description: "A site where I write about my hobby projects."
  keywords: [Blog, Portfolio, PaperMod]
  author: Ivan Guerra
  images: [""]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true
    disableFingerprinting: true
    favicon: "/logo/favicon.ico"
    favicon16x16: "/logo/favicon-16x16.png"
    favicon32x32: "/logo/favicon-32x32.png"
    apple_touch_icon: "/logo/apple_touch_icon.png"
    safari_pinned_tab: ""

  label:
    text: ""
    icon: /logo/favicon.svg
    iconHeight: 40

  homeInfoParams:
    Title: "Ivan Guerra's Website"
    Content: >
      This is my personal website, where I post articles and other stuff,
      usually about coding. All the content you’ll find here is
      extracurricular, so don’t be surprised if you find a bug or two.

  socialIcons:
    - name: github
      url: "https://github.com/ivan-guerra"
    - name: linkedin
      url: "https://linkedin.com/in/ivan-guerra"
    - name: email
      url: "mailto:ivan.eduardo.guerra@gmail.com"
    - name: rss
      url: "https://programmador.com/index.xml"

  editPost:
    URL: "https://github.com/ivan-guerra/programmador.com/tree/master/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30

pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: dracula

outputs:
    home:
        - HTML
        - RSS
        - JSON
