# Credit to GabMus for creating the hugo-ficurinia theme used here. Details
# regarding theme settings (some not shown here) can be found on the official
# project page: https://gitlab.com/gabmus/hugo-ficurinia
baseURL = "https://programmador.com/"
theme = "hugo-ficurinia"
title = "@ieg Dev Log"
languageCode = "en"
defaultContentLanguage = "en"
copyright = """Ivan Guerra - Licensed under
    [MIT](https://github.com/ivan-guerra/programmador.com/blob/master/LICENSE)."""

paginate = 5
summaryLength = 30

[params]
    author = "Ivan Guerra"
    description = "Miscellaneous projects and thoughts on programming and tech."

    posts = "posts"
    showPostsLink = true

    logo = "/logo/logo.svg"
    favicon = "/logo/favicon.png"
    faviconIco = "/logo/favicon.ico"
    appletouch = "/logo/apple-touch-icon.png"
    svgicon = "/logo/logo.svg"
    icon512 = "/logo/icon512.png"
    logoRightOfTitle = true

    showRss = true

    imageInArticlePreview = true
    fitImageInArticlePreview = true
    articleSummary = true

    fontFamily = "JetBrains Mono"
    titleFontFamily = "JetBrains Mono"
    monospaceFontFamily = "JetBrains Mono"

    titleFontSizeMultiplier = 1.0
    mainFontSizeMultiplier = 1.0
    monoFontSizeMultiplier = 1.0

    contentWidth = "1000px"

    buttonTags = true
    tagsInArticlePreview = true
    navtype = "standard"
    enableShadow = true
    menuStyle = "buttons"

    enableSearch = true
    searchbarEverywhere = true
    mobileHamburgerNav = true

    underlineTitleLinks = true

    # TODO: Consider adding support for article comments.
    # commento = "https://example.com/js/commento.js"

    # TODO: Consider adding support for site analytics.

    forceRedirect = true

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/ivan-guerra"
        weight = 10
    [[menu.icons]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://linkedin.com/in/ivan-guerra"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10

